# ============================================================================
# GITHUB COPILOT WORKSPACE CONFIGURATION
# Configuración avanzada para maximizar Copilot Pro+
# ============================================================================

# General Settings
enable_copilot: true
copilot_model: "gpt-4"
advanced_features: true

# Copilot Chat Settings
chat:
  enable: true
  model: "gpt-4-turbo"
  context_window: 128000
  temperature: 0.7
  max_tokens: 4096
  stream_responses: true

# Code Completion
completion:
  enable: true
  inline_suggestions: true
  multi_line_suggestions: true
  suggestion_count: 5
  delay_ms: 50
  tab_completion: true

# Copilot Workspace Features
workspace:
  enable_workspace_context: true
  max_files_context: 100
  max_lines_per_file: 10000
  include_dependencies: true
  semantic_search: true

# AI Agents
agents:
  code_review:
    enable: true
    auto_review_prs: true
    check_security: true
    check_performance: true
    check_best_practices: true

  test_generation:
    enable: true
    auto_generate: true
    coverage_threshold: 80
    frameworks: ["vitest", "playwright"]

  documentation:
    enable: true
    auto_generate: true
    formats: ["jsdoc", "markdown", "inline"]

  refactoring:
    enable: true
    suggest_improvements: true
    detect_code_smells: true

  bug_detection:
    enable: true
    static_analysis: true
    runtime_analysis: true

# GitHub Copilot X Features
copilot_x:
  enable: true

  # Copilot CLI
  cli:
    enable: true
    shell_suggestions: true
    git_suggestions: true

  # Copilot Voice
  voice:
    enable: false

  # Copilot Docs
  docs:
    enable: true
    sources: ["mdn", "react", "typescript", "firebase"]

  # Copilot for Pull Requests
  pull_requests:
    enable: true
    auto_description: true
    auto_review: true
    suggest_reviewers: true

  # Copilot in the CLI
  terminal:
    enable: true
    command_suggestions: true
    error_explanations: true

# Language Models Available
models:
  primary: "gpt-4-turbo"
  fallback: "gpt-3.5-turbo"
  specialized:
    code_generation: "codex"
    code_review: "gpt-4"
    documentation: "gpt-3.5-turbo"
    chat: "gpt-4-turbo"

# Context Enhancement
context:
  use_git_history: true
  use_issue_context: true
  use_pr_context: true
  use_discussion_context: true
  use_wiki_context: true
  use_dependencies: true
  max_context_tokens: 50000

# Security
security:
  enable_vulnerability_scanning: true
  enable_secret_detection: true
  enable_license_compliance: true
  block_insecure_suggestions: true

# Performance
performance:
  cache_suggestions: true
  preload_context: true
  parallel_requests: true
  max_concurrent_requests: 5

# Telemetry
telemetry:
  enable: true
  collect_usage_stats: true
  collect_performance_metrics: true
  send_feedback: true

# Integrations
integrations:
  github_actions: true
  github_codespaces: true
  github_projects: true
  github_discussions: true
  sentry: true
  codecov: true
  firebase: true

# Advanced Features
advanced:
  enable_experimental_features: true
  enable_beta_features: true
  enable_custom_models: false
  enable_fine_tuning: false
