name: 🐞 Bug Report
description: Report a bug or unexpected behavior in the GitHub Copilot CLI.
type: Bug
labels:
  - "triage"
body:
  - type: markdown
    attributes:
      value: |
        <br />
        Thank you for taking the time to report a bug!  Please answer each question below to the best of your ability; it is okay to leave questions blank if you have to.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
  - type: input
    id: version
    attributes:
      label: Affected version
      description: The version of the `copilot` where you encountered the bug (if applicable).
      placeholder: |
        Paste output from `copilot --version`
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: A clear and concise list of steps to reproduce the behavior. Please include any commands you ran and their output.
      placeholder: |
        1. Type '...'
        2. View the output '...'
        3. See error
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        - Logs using `--log-level` and `--log-file` flags
        - Operating system (e.g., Windows, macOS, Linux)
        - CPU architecture (e.g., x86_64, ARM)
        - Terminal emulator (e.g., Terminal, iTerm2, Windows Terminal)
        - Shell (e.g., bash, zsh, fish)
